# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Services Hero
  description: Services Hero
  icon: "i-mdi-account-supervisor-circle-outline"

# Defines the structure of this component, as well as the default values
blueprint:
  id: hero
  title: Our Services
  description: At Maria's Hair Salon, we're thrilled to invite you to experience the ultimate in haircare and styling! Whether you're seeking a fresh new look, a simple trim, or a complete makeover, our talented team of stylists is here to make your hair dreams come true. We offer a wide range of services and fabulous package deals to suit every need and budget. Join us and let us pamper you with top-notch treatments and expert advice. Book your appointment today and discover the beauty that awaits you at Maria's Hair Salon. We can't wait to transform your hair and boost your confidence! Warm regards
  author: Maria, Owner of Maria's Hair Salon
  subtitle: Dear Clients
  image: /images/servicebanner.png
  image_alt:
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  description:
    type: text
    label: Description
  subtitle[*].text:
    type: text
    label: text
  image:
    type: image
    label: Image
  image_alt:
    type: text
    label: Image Alt
