# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Booking Contact
  description: Booking Contact
  icon: "i-mdi-phone"

# Defines the structure of this component, as well as the default values
blueprint:
  id: contact
  title: Contact Us
  image: /images/contact.jpg
  image_alt:
  info:
    - label: Phone
      text: 832-968-6668
    - label: Address
      text: 11011 Richmond Ave, Ste 900, Houston, TX 77042
    - label: Email
      text: contact@fastboy.net
    - label: Opening hours
      text: Monday — Thursday 10:00 – 20:00 <br/> Friday — Sunday 10:00 – 19:00
  button: Book consultation
  background: "#F7F5FF"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  info[*].label:
    type: text
    label: label
  info[*].text:
    type: text
    label: Text
  button:
    type: text
    label: Button
  background:
    type: color
    label: Color Background
  image:
    type: image
    label: Image
  image_alt:
    type: text
    label: Image Alt
