# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Booking Hero
  description: Booking Hero
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
    id: hero
    title: Booking
    image: /images/bookingbanner.png
    image_alt:
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  image:
    type: image
    label: Image
  image_alt:
    type: text
    label: Image Alt
