# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Service Section
  description: Service Section
  icon: "i-mdi-trophy-award"

# Defines the structure of this component, as well as the default values
blueprint:
  id: awards
  title: OUR  AWARDS
  background: "#6C5CE7"
  dataImg:
    - listImg:
        - image: /images/awards1.png
          image_alt:
        - image: /images/awards2.png
          image_alt:
        - image: /images/awards3.png
          image_alt:
    - listImg:
        - image: /images/awards1.png
          image_alt:
        - image: /images/awards2.png
          image_alt:
        - image: /images/awards3.png
          image_alt:
    - listImg:
        - image: /images/awards1.png
          image_alt:
        - image: /images/awards2.png
          image_alt:
        - image: /images/awards3.png
          image_alt:
    - listImg:
        - image: /images/awards1.png
          image_alt:
        - image: /images/awards2.png
          image_alt:
        - image: /images/awards3.png
          image_alt:
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  dataImg[*].listImg.image:
    type: image
    label: Image
  dataImg[*].listImg.image_alt:
    type: text
    label: Image Alt
  background:
    type: color
    label: Color Background
