# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Banner Section
  description: Banner Section
  icon: "i-mdi-home-outline"

# Defines the structure of this component, as well as the default values
blueprint:
  id: banner
  title: LET’S MET THERE
  description: 11011 Richmond Ave, Ste 900, Houston, TX 77042
  subtitle: we open now
  image: /images/banner.png
  image_alt:
  button: make an appointment

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  description:
    type: text
    label: Description
  subtitle:
    type: text
    label: Subtitle
  image:
    type: image
    label: Image
  image_alt:
    type: text
    label: Image Alt
  button:
    type: text
    label: Button
