# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Gallery Section
  description: Gallery Section
  icon: "i-mdi-view-gallery-outline"

# Defines the structure of this component, as well as the default values
blueprint:
  id: gallery
  title: Our Gallery
  background: "#FFFFFF"
  img: /images/gallery6.png
  img_alt:
  description: Sellect title  we will show service’s photos Or <a>See alls</a>
  menuTab:
    - tab: STYLE HAIR
    - tab: HAIR TREATMENT
    - tab: MAKE-UP
  dataImg:
    - image: /images/gallery1.png
      image_alt:
    - image: /images/gallery2.png
      image_alt:
    - image: /images/gallery4.png
      image_alt:
    - image: /images/gallery5.png
      image_alt:
    - image: /images/gallery3.png
      image_alt:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  description:
    type: markdown
    label: Description
  menuTab[*].tab:
    type: text
    label: Title Menu
  img:
    type: image
    label: Image
  img_alt:
    type: text
    label: Image Alt
  dataImg[*].image:
    type: image
    label: Image
  dataImg[*].image_alt:
    type: text
    label: Image Alt
  background:
    type: color
    label: Color Background
