# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Service Section
  description: Service Section
  icon: "i-mdi-account-supervisor-circle-outline"

# Defines the structure of this component, as well as the default values
blueprint:
  id: service
  title: Our Service
  dataImg:
    - listImg:
        - title_img: HAIRCUTS & STYLE
          image: /images/service1.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service2.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service3.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service4.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service5.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service6.png
          image_alt:
    - listImg:
        - title_img: HAIRCUTS & STYLE
          image: /images/service1.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service2.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service3.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service4.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service5.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service6.png
          image_alt:
    - listImg:
        - title_img: HAIRCUTS & STYLE
          image: /images/service1.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service2.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service3.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service4.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service5.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service6.png
          image_alt:
    - listImg:
        - title_img: HAIRCUTS & STYLE
          image: /images/service1.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service2.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service3.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service4.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service5.png
          image_alt:
        - title_img: HAIRCUTS & STYLE
          image: /images/service6.png
          image_alt:
  background: "#F9F5FF"
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  dataImg[*].listImg[*].title_img:
    type: text
    label: Title Image
  dataImg[*].listImg[*].image:
    type: image
    label: Image
  dataImg[*].listImg[*].image_alt:
    type: text
    label: Image Alt
  background:
    type: color
    label: Color Background
