# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Service Section
  description: Service Section
  icon: "i-mdi-gift-outline"

# Defines the structure of this component, as well as the default values
blueprint:
  id: vouchers
  title: Gift Cards/ vouchers
  dataImg:
    - image: /images/vouchers1.png
      image_alt:
    - image: /images/vouchers2.png
      image_alt:
  background: "#FFFAF1"
  button: See more
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  dataImg[*].image:
    type: image
    label: Image
  dataImg[*].image_alt:
    type: text
    label: Image Alt
  background:
    type: color
    label: Color Background
  button:
    type: text
    label: Text Button
